name: Face Mask Detection
description: Face Mask Detection
version: "1.0"
image: myelintek/mask-detection:1.0
gpu: 1
hashtag:
  - face detection
  - mask detection
runtime_params:
  command: ipython3 entry.ipynb
  params:
    batch: 32
    learning_rate: 0.0001
    epochs: 20
    train_dir: '/mlsteam/dala/lab/Face-Mask-Detection/dataset'
    weights_file: 'mask_detector.model'