name: YOLOv4
description: YOLOv4 with wrapper tool
version: "1.1"
image: myelintek/yolov4:1.1
gpu: 1
hashtag:
  - yolov4
  - darknet
  - object detection
volumes:
  - yolo-sample:/mlsteam/data/yolo
runtime_params:
  command: python3 /mlsteam/lab/darknet_wrapper.py
  params:
    output_dir: /mlsteam/data/yolo/model_weights/trained/yolo
    batch: 64
    learning_rate: 0.001
    max_batches: 500
    repeat: 0
    scales: .1; .1
    steps: 400; 450
    subdivisions: 16
    train_dir: /mlsteam/data/yolo/training_data/yolo
    version: tiny
    weights_file: ''
    image_exts: jpg;png
  params_definition:
    version:
      options:
        - tiny
        - original